### ISSUE TITLE
Velocity

### ISSUE THREAD

**Issue by physio** [mgomezarr/AzureFunctions-Nodejs-DInjection#5]
Hi @mgomezarr, thank you for your code. Very interesting. 

I have a question: 
- using the dependency injection into an AZ function (but the same is in AWS lambda), don't I risk slowing down the whole bootstrap part enormously?

Best regards

**Comment by magomzr** [comment]
Hi @physio, my apologies for the late reply.

Naturally there will be a small decrease in performance at startup because we are subjecting the code to a design pattern. However, the real value of using DI lies in the speed that is obtained once the serverless function instance is up. It should be noted that it will also depend on whether we choose an appropriate type of lifetime and registration option (transient, scoped or singleton).
